#!/usr/bin/env bash
# A Bash script that displays a list of all currently running processes in a user-oriented format with hierarchy

ps -axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
