#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely
# and prints OK when receiving SIGTERM signal (does not exit)

trap 'echo OK' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done


