#!/usr/bin/env bash
# Displays "Best School" 10 times; on 9th iteration, also print "Hi" on a new line

count=1
while [ $count -le 10 ]; do
  echo "Best School"
  if [ $count -eq 9 ]; then
    echo "Hi"
  fi
  ((count++))
done
