#!/usr/bin/env bash
# Loops 1-10, prints "bad luck" on 4, "good luck" on 8, "Best School" otherwise

count=1
while [ $count -le 10 ]; do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
