#!/usr/bin/env bash
# Displays the current directory content, showing only the part after the first dash

for file in *; do
  if [[ -f "$file" && "$file" == *-* ]]; then
    echo "${file#*-}"
  fi
done
